### ISSUE TITLE
Multilevel sliding inside the modal

### ISSUE THREAD

**Issue by slopesweb** [k-ivan/glory-modal#40]
Menu: https://codepen.io/johnquimera/pen/BaVbRrq

I'm trying to put this menu in the modal, but the submenu doesn't work inside it. What could be happening?

Modal: https://codepen.io/johnquimera/pen/zYLYOqE

**Comment by k-ivan** [comment]
Thanks for the demo, it saves a lot of time.

The problem is that you are trying to calculate the height of your lists when the modal is closed and has a `display: none`. All elements that are hidden with this property are unsized until the browser renders them on the screen.

You need to calculate the height when the window is shown.
To do this as early as possible, you can do all these manipulations in the event
```js
elem.addEventListener('gmodal:beforeopen', function(evt) {
  // calculates elements sizes
})
```

**Comment by k-ivan** [comment]
Unfortunately, I don’t know anything like that, maybe codepen or github will help you.
